### PR TITLE
SSH enhancements

### LINKED ISSUE #72: SSH service waits 1000 ms between channel polling
Actually 2 issues here:

1. [A constant] (https://github.com/CloudSlang/score-actions/blob/master/score-ssh/src/main/java/io/cloudslang/content/ssh/services/impl/SSHServiceImpl.java#L21) in SSHServiceImpl is configured to 1000 (ms), and is used to define the interval of polling the SSH channel.
2. For some reason the [polling loop] (https://github.com/CloudSlang/score-actions/blob/master/score-ssh/src/main/java/io/cloudslang/content/ssh/services/impl/SSHServiceImpl.java#L132) is a `do .. while` instead of a `while` which means that we wait at least 1 second any way.

this issue has huge impact on cslang flows performance.

@Alex-Persa @meirwah

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #72 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by meirwah** [comment]
@Alex-Persa / @nanebogdan   can you review?

**Comment by Bonczidai** [comment]
as stated previously, huge improvement on flows - e.g. `content/io/cloudslang/docker/maintenance/images_maintenance.sl`:

polling1

**Comment by orius123** [comment]
Awesome!!

**Comment by Bonczidai** [comment]
changes:
- smaller polling interval
- use while loop
- throw TimeoutException (before we only saw returnCode=-1 in logs in case of timeout, no other message)

**Comment by Alex-Persa** [comment]
I reviewed it with Levente. It looks better now (after refactoring) with  more accurate timeout and specific timeout exception.

**Pull request merged**
