### PR TITLE
 HTTP call is pending after N calls

### LINKED ISSUE #80: HTTP call is pending after N calls [2]
I think the issue was the same here - CloudSlang/cloud-slang#437 -

How to reproduce: run https://github.com/CloudSlang/cloud-slang-content/blob/74c618ab25bc28368e0c97ac94f96f279c5f705a/content/io/cloudslang/cloud_provider/digital_ocean/v2/utils/wait_for_status_to_change.sl with inputs:

- droplet_id: `<existing_droplet_id>`
- status: "'active'"
- timeout: 600 # (10 min)
etc.

The params in http_client_action that are related to the issue:
```yaml
    - keepAlive:
        default: "'true'"
    - connectionsMaxPerRoot:
        default: "'2'"
    - connectionsMaxTotal:
        default: "'2'"
```

flow should go on until 10 minutes but it **hangs** at **third** call.

If you set `keepAlive` to **false** it works correctly. Also the number of connections is influencing at which step the flow hangs.

Need to check if:

- this is a bug
- what is the appropriate default value for keepAlive, does false cause slower execution?
- why `connectionsMaxPerRoot` and `connectionsMaxTotal` cannot be higher than 2

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #80 

 Signed-off-by: Claudiu Ban claudiu-laurian.ban@hp.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
@gituser173 please link PR to issue

**Comment by Bonczidai** [comment]
@gituser173 please add test for this case (verify connection is released)

**Comment by oritstone** [comment]
@gituser173  is it ready for review & merge?

**Comment by gituser173** [comment]
No, I want to delete this pull request and create a new one

**Pull request closed without merging**
