### PR TITLE
Release the encryptionKeystore file inputStream so the operation won't lock the file. Added validations for EncryptionKeyAlias and for attachment inputs. SendMailOperation now will encript attachments too when EncryptionKeystore input is set. Added enableTLS input for send mail operation. Signed of by dan-alexandru.persa@hp.com 

### PR DESCRIPTION
**Pull request by Alex-Persa**
Added some extra negative scenarios validations.

### CODE REVIEW

**Comment by meirwah** [comment]
where are the tests for those?

**Comment by Alex-Persa** [comment]
In progress.

**Comment by meirwah** [comment]
Please verify relevent flows still work...

**Comment by Alex-Persa** [comment]
I didn't find any .sl flow using email operations. Only a operation "cloud-slang-content/content/io/cloudslang/base/mail/send_mail.sl". I've created locally a test flow which uses this operation with the new code and it works fine agains our smtp environment.

**Comment by meirwah** [comment]
@tudorlesan please see it fixes your SMTP issue

**Comment by tudorlesan** [comment]
@meirwah I made a pull request that fixes my problem. I also showed it to @Alex-Persa and he said that this is unrelated. My fix works only for my particular case, but adding an input which can be true/false solves it. That needs to be done for using smtp servers that use TLS

**Comment by Alex-Persa** [comment]
@tudorlesan @meirwah I just added the input and capabilitis for sending emails against TLS smtp servers. @tudorlesan I think you cand close your pull request because that way the operation won't work against non tls servers and the backward compatibility will be broke.

**Comment by tudorlesan** [comment]
@Alex-Persa will do. thanks :)

**Pull request merged**
