### PR TITLE
Amazon AWS EC2 Enhancements

### PR DESCRIPTION
**Pull request by mihaitusa**
Enhancements for "Describe Instances in Region" to support advance filtering (agm12788).

### CODE REVIEW

**Comment by mihaitusa** [comment]
@gituser173 Please review it!

**Comment by mihaitusa** [comment]
@gituser173 If the review is done... you can merge it.

**Comment by mihaitusa** [comment]
@gituser173 Now if everything is OK from review than you should merge it. Thanks!

**Comment by gituser173** [comment]
replace methods that do String splitting with StringUtils.split

**Comment by mihaitusa** [comment]
@gituser173 Done... I will reuse it from now one...

**Pull request merged**
