### PR TITLE
Remote file transfer

### PR DESCRIPTION
**Pull request by tudorlesan**
Signed-off-by: Lesan Tudor <tudor-andrei.lesan@hp.com>

### CODE REVIEW

**Comment by oritstone** [comment]
Is it a duplicate of PR #63?

**Comment by tudorlesan** [comment]
yes, sorry, I forgot about that one. I'm working on this one though, so #63 can be deleted

**Comment by orius123** [comment]
@tudorlesan 
cant we delete the branch?

**Comment by tudorlesan** [comment]
@orius123 I think so. If other functionalities should be added, a different branch can be created.

**Pull request merged**
